#+TITLE: Title
#+AUTHOR: Author name
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS:   ^:nil
#+STARTUP: hideblocks
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:

#+LaTeX_CLASS: nusthesis
#+LaTeX_HEADER: \subtitle{subtitle}
#+LaTeX_HEADER:	\prevdegrees{B.Sci. (Hons), NUS, 2008 \\ M.Comp, NUS, 2011}
#+LaTeX_HEADER: \university{National University of Singapore}
#+LaTeX_HEADER: \department{Department}
#+LaTeX_HEADER: \degree{Doctor of Philosophy}
#+LaTeX_HEADER: \supervisor{Prof.}
#+LaTeX_HEADER: \submityear{2013}
#+LaTeX_HEADER: \keywords{keywords}

#+LaTeX_HEADER: \let\itemize\compactitem
#+LaTeX_HEADER: \let\description\compactdesc
#+LaTeX_HEADER: \let\enumerate\compactenum  
#+LaTeX_HEADER: \onehalfspacing

#+BIBLIOGRAPHY: ref plain limit:t

#+LaTeX: \pagenumbering{roman}
#+NAME: Declaration
#+BEGIN_LaTeX
\declaration{
\indent I hereby declare that this thesis is my original work and it has been written by me in its entirety. \\
\indent I have duly acknowledged all the sources of information which have been used in the thesis. \vspace{0.5cm} \\
This thesis has also not been submitted for any degree in any university previously.
}
#+END_LaTeX

#+NAME: Acknowledgement
#+BEGIN_LaTeX
\acknowledgment{
Foremost, I would like to express my sincere gratitude to my advisor Prof.  for the continuous support of my Ph.D study and research, for his patience, motivation, enthusiasm, and immense knowledge. His guidance helped me in all the time of research and writing of this thesis.

Besides my advisor, I would like to thank the rest of my thesis committee: Prof., for their encouragement, insightful comments, and hard questions.

My sincere thanks also goes to Dr. , for offering me the summer internship opportunities in their groups and leading me working on diverse exciting projects.

I thank my fellow labmates in Group: , for the stimulating discussions, for the sleepless nights we were working together before deadlines, and for all the fun we have had in the last four years. 

Last but not the least, I would like to thank my family
}
#+END_LaTeX

#+NAME: TOC
#+BEGIN_LaTeX
\tableofcontents
#+END_LaTeX

#+NAME: Abstract
#+BEGIN_LaTeX
\newpage
\abstract{
abstract page
}
#+END_LaTeX
#+NAME: ListOfFiguresAndTables
#+BEGIN_LaTeX
\listoftables
\listoffigures
#+END_LaTeX


* Figure and Table Tests
  :PROPERTIES:
  :NUMBERED: n
  :END:
#+LaTeX: \pagenumbering{arabic}
** Figure
   :PROPERTIES:
   :NUMBERED: n
   :END:

some text. some text.
#+LABEL: hist
#+BEGIN_SRC R :exports both :results graphics :file test1.pdf 
  hist(rnorm(1000))
#+END_SRC

#+CAPTION: figure 1
#+RESULTS:
[[file:test1.pdf]]

#+LABEL: pie
#+BEGIN_SRC R :exports both :results graphics :file test2.pdf 
  pie(1:7)
#+END_SRC

#+CAPTION: figure 2
#+RESULTS:
[[file:test2.pdf]]

** Table
   #+CAPTION: A wide table with tabulary
   #+LABEL: tbl:wide
   #+ATTR_LaTeX: table* tabulary width=\textwidth
   | ..... | ..... |
   | ..... | ..... |

#+BEGIN_LaTeX
\begin{table}[ht]
\caption{Dummy table 1}
\begin{center}
\begin{tabular}{|c|c|}
a & b
1 & 2
\end{tabular}
\end{center}
\label{tab:dum1}
\end{table}
#+END_LaTeX
** Citation
Some reference \cite{pmid23396134}
* README
** Requirements
- Tested in emacs 24.2, 24.3
- Orgmode > 8.0 (new exporter)
- make
** Usage
For emacs orgmode users, running "make" will export the orgmode document to pdf. Figures in org file will not be generated during export, so you need to generate them before export.
Multilpe rounds of "make" may be necessary to generate the list of tables, list of figures and bibliography successfully.
For LaTeX user, nusthesis.cls and thesis.tex can be used as templates.

* Another chapter 					      :ignoreheading:
ignoreheading fix is not yet in the master branch.

#+LaTeX: \newpage
#+LaTeX: \bibliographystyle{plain}
#+LaTeX: \bibliography{ref}

#+LaTeX: \newpage
#+LaTeX: \appendix
#+LaTeX: \addappheadtotoc
#+LaTeX: \appendixpage

** appendix chapter 1
some text
** appendix chapter 2
some text



